application: smartguide
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/spi/.*
  script: main.api

- url: /shape_files
  static_dir: shape_files

libraries:
- name: endpoints
  version: "latest"
- name: protorpc
  version: "latest"

